version: 2
  jobs:
    build:
      branches:
        only:
          - master
          - development
        docker:
          - image: circleci/node:8.0
          - image: docker:17.09.1-ce-git  # enable the docker build support
       working_directory: ~/repo
         steps:
           - checkout
           - setup_remote_docker
           - restore_cache:
             keys:
               - v1-dependencies-{{ checksum "package.json" }}
               - v1-dependencies-
    
          # clearing the cache
          - run: yarn cache clear --force
          # - run: rm package-lock.json
          - run: yarn install
          - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
          # run tests!
          - run: yarn run test
          # build the docker image on success
          - run:
            name: Build Success
            when: on_success
            command: |
              docker --version
              docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD
              docker build --tag carrott/backendservices:$CIRCLE_BRANCH --build-arg MACHINE_NAME=backendservices-$CIRCLE_BRANCH .
              docker push carrott/backendservices:$CIRCLE_BRANCH
              echo "Docker build made sucessfully!! for backendservices $CIRCLE_BRANCH"
          - run:
            name: Build Failure
            when: on_fail
            command: |
              echo "ERROR building <application_name> $CIRCLE_BRANCH"