const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
const USER_CREATED = "USER_CREATED";
const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
const VALIDATION_ERROR = "VALIDATION_ERROR";
const USER_NOT_FOUND = "USER_NOT_FOUND";
const VALIDATE_SUCCESS = "VALIDATE_SUCCESS";
const PASSWORD_SUCCESS = "PASSWORD_SUCCESS";
const PASSWORD_NOMATCH = "PASSWORD_NOMATCH";
const PASSWORD_INCORRECT = "PASSWORD_INCORRECT";
const EMAIL_SENT = "EMAIL_SENT";

module.exports = {
  INVALID_CREDENTIALS,
  USER_CREATED,
  EMAIL_ALREADY_EXISTS,
  VALIDATION_ERROR,
  USER_NOT_FOUND,
  VALIDATE_SUCCESS,
  PASSWORD_SUCCESS,
  PASSWORD_NOMATCH,
  PASSWORD_INCORRECT,
  EMAIL_SENT,
};
