const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
const USER_CREATED = "USER_CREATED";
const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
const VALIDATION_ERROR = "VALIDATION_ERROR";
const USER_NOT_FOUND = "USER_NOT_FOUND";

module.exports = {
  INVALID_CREDENTIALS,
  USER_CREATED,
  EMAIL_ALREADY_EXISTS,
  VALIDATION_ERROR,
  USER_NOT_FOUND,
};
